version: '2'

services:
  magetwo:
    image: magetwo:7.1
    container_name: "magetwo"
    hostname: magetwo
    network_mode: bridge
    environment:
      SERVER_NAME: magetwo.local
      PHP_TIMEZONE: "Asia/Jakarta"
      PHP_MEMORY_LIMIT: "1G"
      ENABLE_CRON: "yes"
      ENABLE_VARNISH: "yes"
      ENABLE_IONCUBE: "yes"
    ports:
      - 2202:2202
    volumes:
      - /var/data/magento:/magento/website
