version: '2'

services:
  magetwo:
    image: fauzie/magetwo:latest
    container_name: "magetwo"
    hostname: magetwo
    network_mode: bridge
    environment:
      SERVER_NAME: magetwo.local
      PHP_TIMEZONE: "Asia/Jakarta"
      ENABLE_IONCUBE: "1"
      ENABLE_CRON: "1"
    volumes:
      - /home/fauzie/Public/vuemage:/magento/website
