version: '2'

services:
  magetwo:
    image: magetwo:7.2
    container_name: "magetwo"
    hostname: magetwo
    network_mode: bridge
    environment:
      VIRTUAL_HOST: magetwo.dock
      PHP_OPCACHE_ENABLE: "On"
      PHP_TIMEZONE: "Asia/Jakarta"
      PHP_MEMORY_LIMIT: "1G"
      ENABLE_CRON: "yes"
      ENABLE_VARNISH: "yes"
      ENABLE_IONCUBE: "yes"
    ports:
      - 2202:2202
    volumes:
      - /home/fauzie/Public/magetwo:/magento/website
